#!/usr/bin/env bash
# Define the key name, passphrase, and key size
KEY_NAME="school"
PASSPHRASE="betty"
KEY_SIZE=4096
# Generate the SSH key pair
ssh-keygen -t rsa -b $KEY_SIZE -f $KEY_NAME -N "$PASSPHRASE" -q
# Output success message
echo "SSH key pair '$KEY_NAME' and '$KEY_NAME.pub' created successfully!"
