#!/usr/bin/env bash
#servers are the piece of softwaregeneratingg and serving html pages.
#installing nginx the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo  "hello world " > /var/www/html/index.html'
service nginx restart
